### PR TITLE
load the urdf file into rosparam

### PR DESCRIPTION
**Pull request by liniii31**

### CODE REVIEW

**Comment by longjie0723** [comment]
Loading a primitive shape (cylinder) is done. Now replace it by some mesh files. 

You can find many mesh file on the net. For example, this site. 
https://www.thingiverse.com/
You can visually see the mesh files using an utility named 'meshlab' .

Or I recommend to create your own mesh file by CAD. There are several free CAD software.

**Comment by liniii31** [comment]
yes Done.please check

**Comment by longjie0723** [comment]
@liniii31 
How did you create your mesh file? It looks like just a ring facing the frontal direction.

You can make any shape or can borrow any shape from the internet, why don't you make it more impressive? For example you can create mobile robots combining the ring with some bodies if you intent and search for how.

This is a technical assignment, but similar to other actual, real jobs, you are expected to do your BEST. It is up to  you how deep knowledge you can get from the assignments. 

- make the shape more impressive
- put the URDF files in urdf subdirectory

**Comment by liniii31** [comment]
I have added a new commit with the following improvements:
 - I have added two services in the same node to start and stop the circular motion. **"rosservice call start"** will start the tf broadcasting and **"rosservice call stop"** will stop the broadcasting.
 -  I made an shape(took help from online materials) in the FreeCAD software and then exported it in .dae mesh files, which i further used in urdf.
Please Check.

**Comment by longjie0723** [comment]
`roslaunch ros_learning circle.launch` produce errors:

```
Traceback (most recent call last):
  File "/home/tajima/Codes/test_ws/src/ros_learning/nodes/moving_frame.py", line 70, in <module>
    publisher(omega,radius,rate)
  File "/home/tajima/Codes/test_ws/src/ros_learning/nodes/moving_frame.py", line 57, in publisher
    s1= rospy.Service('start',start,start_service)
NameError: global name 'start' is not defined
[moving_frame-2] process has died [pid 17219, exit code 1, cmd /home/tajima/Codes/test_ws/src/ros_learning/nodes/moving_frame.py __name:=moving_frame __log:=/home/tajima/.ros/log/fdca2a6e-4eea-11eb-8c68-380025ad3c75/moving_frame-2.log].
log file: /home/tajima/.ros/log/fdca2a6e-4eea-11eb-8c68-380025ad3c75/moving_frame-2*.log
```

Please take time to check your code before pushing. This is not a quiz, but a learning. Taking some time to research and lean is not a problem.

**Comment by liniii31** [comment]
Yes sir, I did check the code before pushing, there was no error.
I checked it again , it works fine on my system, and am not getting any error.

**Comment by longjie0723** [comment]
Sorry my bad, I forgot to rebuild, so the files for the service were not generated. After rebuilding, the error is gone.
One thing for this, it is a custom in python to capitalize the class name. 'start' is the class name of the service, so it should be capitalized. So 'start.srv' should be renamed to  'Start.srv' Please see the other ROS services and notice they are all capitalized. 
 
However, even this error gone, the function is not enough for the request. The map frame is not published when it start. When the start service called, robot jumps to the start point, and it blocks service call forever. In general, ROS's service should be minimal, and should not block the caller for long time.

In this case you don't need to change the main loop structure of the node from the previous version. You are using a global variable ('flag') to start/stop the robot, so please just refer it in the main loop ('publisher') to change the robot motion.

FYI:
When you need a trigger service like this request, we can use [std_srvs/Trigger service](http://docs.ros.org/en/melodic/api/std_srvs/html/srv/Trigger.html).

**Comment by liniii31** [comment]
I have done the improvements.Please check

**Comment by longjie0723** [comment]
Cute. I have checked it works and satisfy the request. Please merge this and close #5 and #7.

One thing on this node, the global 'flag' can be eliminated by using Class. I'll make another pull request on this, but now please move on to #11.

**Pull request merged**
