### PR TITLE
Adding a robot arm

### PR DESCRIPTION
**Pull request by liniii31**

### CODE REVIEW

**Comment by longjie0723** [comment]
- The units in ROS is SI units, so the size should be in meters. The mesh files seems have size in milimeters. Use scale argument
- Please add 'tool' frame on the tip of link_3, as the tool frame of the robot

**Comment by longjie0723** [comment]
Size and tool frame looks good.
I noticed this robot model has only three joints. 
SCARA robot has fourth joint to rotate the final axis after the prismatic joint. Please add that joint.

**Comment by liniii31** [comment]
Please check.

**Comment by longjie0723** [comment]
For now, it publishes the IK result on /joint_pose, right? It is differ from the joint_states, so something wrong.

I notice the base_frame is not on the mesh's center of the base. It may cause the difference.

**Pull request merged**
